
CREATE TABLE public.oportunities_three_levels_third_strategy (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  exchange text null,
  start_asset text null,
  triangle_path text null,
  profit_percentage numeric null,
  estimated_profit numeric null,
  estimated_profit_currency text null,
  multiplier numeric null,
  notional_amount numeric null,
  fee_per_trade numeric null,
  legs jsonb null,
  timestamp timestamp without time zone null,
  timestamp_ms bigint null,
  final_amount numeric null,
  start_amount numeric null,
  constraint oportunities_three_levels__third_strategy_pkey primary key (id)
);

ALTER TABLE public.oportunities_three_levels_third_strategy ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public.oportunities_three_levels_third_strategy
  FOR SELECT USING (true);
